{"name": "test_method_2", "status": "failed", "statusDetails": {"message": "AssertionError: Assertion failed, Expected 7\nassert (5 + 2) == 2", "trace": "def test_method_2():\n        x = 5\n        y = 2\n        assert \"Tom\" == \"Tom\", \"Assertion failed, Expected 7 but was\" + str(x + y)\n>       assert x + y == 2, \"Assertion failed, Expected 7\"\nE       AssertionError: Assertion failed, Expected 7\nE       assert (5 + 2) == 2\n\npytest_project\\test_pytest2.py:7: AssertionError"}, "start": 1669994112599, "stop": 1669994112599, "uuid": "2b913e20-0132-4aed-b87c-661a755d1c83", "historyId": "69704c47c26d9943c02bb16b71565cdd", "testCaseId": "7d964a7d98bd20d03649dc9b1bd341b2", "fullName": "pytest_project.test_pytest2#test_method_2", "labels": [{"name": "parentSuite", "value": "pytest_project"}, {"name": "suite", "value": "test_pytest2"}, {"name": "host", "value": "DESKTOP-OM28FAJ"}, {"name": "thread", "value": "7416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_project.test_pytest2"}]}